rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n%ex

logger.spark.name = org.apache.spark
logger.spark.level = info

logger.repl.name = org.apache.spark.repl.Main
logger.repl.level = warn

logger.jetty1.name = org.sparkproject.jetty
logger.jetty1.level = warn

logger.parquet.name = org.apache.parquet
logger.parquet.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn
